#!/bin/bash

FILE="$HOME/.local/share/applications/sscalc-gui.desktop"

echo ".desktop file = ${FILE}"

{
  echo "[Desktop Entry]"
  echo "Version=1.0"
  echo "Type=Application"
  echo "Terminal=false"
  echo "Exec=env LC_ALL=\"en_US.UTF-8\" $HOME/.local/bin/sscalc-gui"
  echo "TryExec=$HOME/.local/bin/sscalc-gui"
  echo "Name=SSCalc"
  echo "GenericName=Calculator"
  echo "Comment=Simple Scientific Calculator"
  echo "Icon=sscalc"
  echo "StartupNotify=true"
  echo "StartupWMClass=sscalc-gui"
  echo "Categories=Utility;Calculator;"
  echo "Keywords=calculator;arithmetic;scientific;"
  echo "Keywords[es]=calculadora;aritmética;científica;"
} > "${FILE}"


