build:
	make -C libstring
	make -C libstd
	make -C libmaths
	make -C libcalc 

install:
	make -C libstring install
	make -C libstd install
	make -C libmaths install
	make -C libcalc install

clean:
	make -C libstring clean
	make -C libstd clean
	make -C libmaths clean
	make -C libcalc clean

clean_build:
	make -C libstring clean_build
	make -C libstd clean_build
	make -C libmaths clean_build
	make -C libcalc clean_build